"""
sources.py — 精选新闻源
聚焦：半导体 / 算力 / 材料 / 人工智能 / 投资产业链
共 120 个源，6层分级，权重 7-10
"""

# ══════════════════════════════════════════════════════
# Tier 1 · 顶级财经媒体（14个）权重8-10
# ══════════════════════════════════════════════════════
TIER1_FINANCIAL = [
    {"name": "Bloomberg 彭博社",
     "weight": 10, "tags": ["macro","finance","semiconductor","AI"],
     "url": "https://news.google.com/rss/search?q=when:48h+allinurl:bloomberg.com+AI+OR+semiconductor+OR+chip+OR+nvidia+OR+tsmc&ceid=US:en&hl=en-US&gl=US"},
    {"name": "Reuters 路透社",
     "weight": 10, "tags": ["macro","geopolitics","semiconductor"],
     "url": "https://news.google.com/rss/search?q=when:48h+allinurl:reuters.com+chip+OR+AI+OR+semiconductor+OR+materials&ceid=US:en&hl=en-US&gl=US"},
    {"name": "Financial Times 金融时报",
     "weight": 10, "tags": ["finance","tech","analysis"],
     "url": "https://news.google.com/rss/search?q=when:48h+allinurl:ft.com+AI+OR+semiconductor+OR+chip+OR+China+tech&ceid=US:en&hl=en-US&gl=US"},
    {"name": "Wall Street Journal",
     "weight": 9,  "tags": ["finance","tech","investment"],
     "url": "https://news.google.com/rss/search?q=when:48h+allinurl:wsj.com+AI+OR+chip+OR+semiconductor+OR+funding&ceid=US:en&hl=en-US&gl=US"},
    {"name": "The Economist 经济学人",
     "weight": 9,  "tags": ["macro","analysis","deep-dive"],
     "url": "https://news.google.com/rss/search?q=when:48h+allinurl:economist.com+AI+OR+semiconductor+OR+China+tech&ceid=US:en&hl=en-US&gl=US"},
    {"name": "Bloomberg Tech RSS",
     "weight": 9,  "tags": ["tech","AI","semiconductor"],
     "url": "https://feeds.bloomberg.com/technology/news.rss"},
    {"name": "The Diff (Byrne Hobart)",
     "weight": 9,  "tags": ["macro","finance","deep-dive"],
     "url": "https://www.thediff.co/feed/"},
    {"name": "Stratechery (Ben Thompson)",
     "weight": 10, "tags": ["tech","strategy","AI"],
     "url": "https://stratechery.com/feed/"},
    {"name": "Ben Evans Newsletter",
     "weight": 9,  "tags": ["tech","strategy","VC"],
     "url": "https://www.ben-evans.com/benedictevans/rss.xml"},
    {"name": "MIT Technology Review",
     "weight": 9,  "tags": ["AI","materials","deep-dive"],
     "url": "https://www.technologyreview.com/feed/"},
    {"name": "Wired 科技深度",
     "weight": 8,  "tags": ["AI","tech","society"],
     "url": "https://www.wired.com/feed/tag/ai/latest/rss"},
    {"name": "New York Times Tech",
     "weight": 8,  "tags": ["tech","AI","policy"],
     "url": "https://news.google.com/rss/search?q=when:48h+allinurl:nytimes.com+AI+OR+chip+OR+semiconductor&ceid=US:en&hl=en-US&gl=US"},
    {"name": "Axios Tech",
     "weight": 8,  "tags": ["tech","AI","policy"],
     "url": "https://www.axios.com/feeds/feed.rss"},
    {"name": "Yahoo Finance 科技板块",
     "weight": 7,  "tags": ["stocks","finance","earnings"],
     "url": "https://finance.yahoo.com/news/rssindex"},
]

# ══════════════════════════════════════════════════════
# Tier 2 · 半导体 / 芯片 / 算力专项（28个）权重8-10
# 核心聚焦：这是你最重要的领域
# ══════════════════════════════════════════════════════
TIER2_SEMICONDUCTOR = [
    # 顶级分析机构
    {"name": "SemiAnalysis（Dylan Patel）",
     "weight": 10, "tags": ["semiconductor","AI","supply-chain","HBM"],
     "url": "https://semianalysis.com/feed/"},
    {"name": "Asianometry 半导体史",
     "weight": 10, "tags": ["semiconductor","history","China","TSMC"],
     "url": "https://newsletter.asianometry.com/feed"},
    # 行业权威媒体
    {"name": "IEEE Spectrum",
     "weight": 10, "tags": ["semiconductor","engineering","AI"],
     "url": "https://spectrum.ieee.org/feeds/feed.rss"},
    {"name": "EE Times 半导体",
     "weight": 10, "tags": ["semiconductor","chips","design"],
     "url": "https://www.eetimes.com/feed/"},
    {"name": "Semiconductor Engineering",
     "weight": 10, "tags": ["semiconductor","EDA","process","packaging"],
     "url": "https://semiengineering.com/feed/"},
    {"name": "AnySilicon 半导体服务",
     "weight": 9,  "tags": ["semiconductor","ASIC","IP","supply-chain"],
     "url": "https://anysilicon.com/feed/"},
    {"name": "Semiconductor Today",
     "weight": 9,  "tags": ["semiconductor","compound","GaN","SiC"],
     "url": "https://www.semiconductor-today.com/rss/news.rss"},
    {"name": "SIA 半导体协会",
     "weight": 9,  "tags": ["semiconductor","industry","sales","policy"],
     "url": "https://www.semiconductors.org/rss/"},
    {"name": "Fierce Electronics",
     "weight": 8,  "tags": ["electronics","semiconductor","IoT"],
     "url": "https://www.fierceelectronics.com/rss/xml"},
    {"name": "Tom's Hardware GPU/CPU",
     "weight": 8,  "tags": ["GPU","CPU","hardware","benchmark"],
     "url": "https://www.tomshardware.com/feeds/all"},
    {"name": "The Register 硬件",
     "weight": 8,  "tags": ["hardware","chips","datacenter"],
     "url": "https://www.theregister.com/headlines.atom"},
    # 算力/数据中心
    {"name": "Data Center Dynamics",
     "weight": 9,  "tags": ["datacenter","AI-infra","power","cooling"],
     "url": "https://www.datacenterdynamics.com/en/rss/"},
    {"name": "Data Center Knowledge",
     "weight": 8,  "tags": ["datacenter","cloud","AI","power"],
     "url": "https://www.datacenterknowledge.com/feed"},
    {"name": "Blocks & Files 存储",
     "weight": 8,  "tags": ["storage","HBM","DRAM","flash"],
     "url": "https://blocksandfiles.com/feed/"},
    # Google News 半导体专项
    {"name": "GNews: NVIDIA GPU AI算力",
     "weight": 10, "tags": ["GPU","NVIDIA","compute","H100","Blackwell"],
     "url": "https://news.google.com/rss/search?q=when:48h+NVIDIA+GPU+Blackwell+OR+H100+OR+B200+OR+Rubin+AI+chip&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: TSMC台积电",
     "weight": 10, "tags": ["TSMC","foundry","3nm","2nm","CoWoS"],
     "url": "https://news.google.com/rss/search?q=when:48h+TSMC+台积电+foundry+semiconductor+advanced+packaging&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: AMD Intel芯片",
     "weight": 9,  "tags": ["AMD","Intel","CPU","GPU","foundry"],
     "url": "https://news.google.com/rss/search?q=when:48h+AMD+OR+Intel+semiconductor+chip+AI+GPU+datacenter&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: HBM高带宽内存",
     "weight": 10, "tags": ["HBM","memory","SKhynix","Samsung","Micron"],
     "url": "https://news.google.com/rss/search?q=when:48h+HBM+high+bandwidth+memory+SK+Hynix+Samsung+Micron+AI&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 先进封装CoWoS/Chiplet",
     "weight": 10, "tags": ["packaging","CoWoS","chiplet","3D-IC","SoIC"],
     "url": "https://news.google.com/rss/search?q=when:48h+advanced+packaging+CoWoS+chiplet+3D+IC+EMIB+SoIC&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: ASML光刻机EUV",
     "weight": 10, "tags": ["ASML","EUV","lithography","export-control"],
     "url": "https://news.google.com/rss/search?q=when:48h+ASML+EUV+lithography+chip+export+Netherlands&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 数据中心算力建设",
     "weight": 10, "tags": ["datacenter","AI-infra","compute","power","gigawatt"],
     "url": "https://news.google.com/rss/search?q=when:48h+AI+data+center+gigawatt+OR+billion+compute+infrastructure+power&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 出口管制芯片禁令",
     "weight": 9,  "tags": ["export-control","ban","semiconductor","US-China"],
     "url": "https://news.google.com/rss/search?q=when:48h+chip+export+control+ban+US+China+semiconductor+restriction&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 国产芯片算力",
     "weight": 10, "tags": ["China","chip","domestic","Huawei","Ascend"],
     "url": "https://news.google.com/rss/search?q=when:48h+华为昇腾+OR+寒武纪+OR+海光+OR+国产GPU+OR+国产芯片+算力&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "GNews: 中国半导体产业",
     "weight": 10, "tags": ["China","semiconductor","fab","SMIC","self-sufficiency"],
     "url": "https://news.google.com/rss/search?q=when:48h+China+semiconductor+fab+SMIC+chip+domestic+supply+chain&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 量子计算芯片",
     "weight": 8,  "tags": ["quantum","computing","chip","Google","IBM"],
     "url": "https://news.google.com/rss/search?q=when:48h+quantum+computing+chip+qubit+IBM+Google+Microsoft&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 光子芯片互联",
     "weight": 8,  "tags": ["photonics","optical","interconnect","CPO"],
     "url": "https://news.google.com/rss/search?q=when:48h+photonic+chip+optical+interconnect+co-packaged+optics&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 边缘AI芯片",
     "weight": 8,  "tags": ["edge-AI","inference","mobile","Qualcomm","Apple"],
     "url": "https://news.google.com/rss/search?q=when:48h+edge+AI+chip+inference+Qualcomm+Apple+Samsung+neural&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: AI能源电力",
     "weight": 9,  "tags": ["AI","energy","power","nuclear","electricity"],
     "url": "https://news.google.com/rss/search?q=when:48h+AI+data+center+energy+power+electricity+nuclear+renewable&ceid=US:en&hl=en-US&gl=US"},
]

# ══════════════════════════════════════════════════════
# Tier 3 · 人工智能专项（24个）权重8-10
# ══════════════════════════════════════════════════════
TIER3_AI = [
    # 大厂官方博客
    {"name": "OpenAI 官方博客",
     "weight": 10, "tags": ["AI","LLM","GPT","AGI"],
     "url": "https://openai.com/news/rss.xml"},
    {"name": "Anthropic 官方新闻",
     "weight": 10, "tags": ["AI","Claude","safety"],
     "url": "https://www.anthropic.com/news/rss"},
    {"name": "Google DeepMind",
     "weight": 9,  "tags": ["AI","research","AGI","Gemini"],
     "url": "https://deepmind.google/blog/rss.xml"},
    {"name": "Meta AI Blog",
     "weight": 9,  "tags": ["AI","LLM","open-source","Llama"],
     "url": "https://ai.meta.com/blog/rss/"},
    {"name": "NVIDIA 开发者博客",
     "weight": 9,  "tags": ["GPU","AI","compute","CUDA"],
     "url": "https://blogs.nvidia.com/feed/"},
    {"name": "Hugging Face 博客",
     "weight": 9,  "tags": ["AI","open-source","models"],
     "url": "https://huggingface.co/blog/feed.xml"},
    # 顶级独立分析师
    {"name": "Import AI (Jack Clark)",
     "weight": 9,  "tags": ["AI","policy","safety"],
     "url": "https://importai.substack.com/feed"},
    {"name": "Interconnects (Nathan Lambert)",
     "weight": 9,  "tags": ["AI","LLM","RLHF","training"],
     "url": "https://www.interconnects.ai/feed"},
    {"name": "Epoch AI 算力趋势",
     "weight": 9,  "tags": ["AI","compute","scaling","trends"],
     "url": "https://epochai.org/feed.xml"},
    {"name": "Ahead of AI (Raschka)",
     "weight": 8,  "tags": ["AI","LLM","practitioner"],
     "url": "https://magazine.sebastianraschka.com/feed"},
    # 学术
    {"name": "arXiv cs.AI",
     "weight": 8,  "tags": ["AI","papers","research"],
     "url": "https://rss.arxiv.org/rss/cs.AI"},
    {"name": "arXiv cs.LG 机器学习",
     "weight": 8,  "tags": ["ML","papers","research"],
     "url": "https://rss.arxiv.org/rss/cs.LG"},
    {"name": "Papers With Code",
     "weight": 8,  "tags": ["AI","papers","SOTA"],
     "url": "https://paperswithcode.com/rss"},
    {"name": "BAIR Blog 伯克利AI",
     "weight": 8,  "tags": ["AI","robotics","research"],
     "url": "https://bair.berkeley.edu/blog/feed.xml"},
    # Google News AI专项
    {"name": "GNews: 大模型发布训练",
     "weight": 10, "tags": ["LLM","release","training","benchmark"],
     "url": "https://news.google.com/rss/search?q=when:48h+large+language+model+LLM+release+training+benchmark+AI&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: AI推理部署",
     "weight": 9,  "tags": ["inference","deployment","efficiency","quantization"],
     "url": "https://news.google.com/rss/search?q=when:48h+AI+inference+deployment+efficiency+quantization+latency&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: AI智能体Agent",
     "weight": 9,  "tags": ["AI-agent","autonomous","workflow"],
     "url": "https://news.google.com/rss/search?q=when:48h+AI+agent+autonomous+agentic+workflow+tool-use&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 国产大模型",
     "weight": 10, "tags": ["China","AI","LLM","DeepSeek","Qwen"],
     "url": "https://news.google.com/rss/search?q=when:48h+DeepSeek+OR+Qwen+OR+Kimi+OR+Doubao+OR+Hunyuan+AI+model+China&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 多模态视觉AI",
     "weight": 8,  "tags": ["multimodal","vision","video","AI"],
     "url": "https://news.google.com/rss/search?q=when:48h+multimodal+vision+video+AI+model+image+generation&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: AI开源模型",
     "weight": 9,  "tags": ["open-source","LLM","weights","community"],
     "url": "https://news.google.com/rss/search?q=when:48h+open+source+AI+model+weights+release+Llama+Mistral&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: AI监管政策",
     "weight": 8,  "tags": ["AI","regulation","policy","EU","US"],
     "url": "https://news.google.com/rss/search?q=when:48h+AI+regulation+policy+government+EU+AI+Act+executive+order&ceid=US:en&hl=en-US&gl=US"},
    {"name": "VentureBeat AI",
     "weight": 8,  "tags": ["AI","industry","enterprise"],
     "url": "https://venturebeat.com/category/ai/feed/"},
    {"name": "The Decoder AI新闻",
     "weight": 8,  "tags": ["AI","news","analysis"],
     "url": "https://the-decoder.com/feed/"},
    {"name": "AI Business 企业AI",
     "weight": 7,  "tags": ["AI","enterprise","business"],
     "url": "https://aibusiness.com/rss.xml"},
]

# ══════════════════════════════════════════════════════
# Tier 4 · 材料科学 / 先进制造 / 机器人（20个）权重7-10
# 这是你专业背景，重点强化
# ══════════════════════════════════════════════════════
TIER4_MATERIALS_ROBOTICS = [
    # 材料科学权威
    {"name": "Nature Materials",
     "weight": 10, "tags": ["materials","research","science","Nature"],
     "url": "https://www.nature.com/nmat.rss"},
    {"name": "Advanced Materials (Wiley)",
     "weight": 10, "tags": ["materials","polymer","nanotech","research"],
     "url": "https://onlinelibrary.wiley.com/feed/15214095/most-recent"},
    {"name": "Materials Today",
     "weight": 9,  "tags": ["materials","research","industry","advanced"],
     "url": "https://www.materialstoday.com/rss/news/"},
    {"name": "C&EN 化学工程新闻",
     "weight": 9,  "tags": ["chemistry","materials","semiconductor","battery"],
     "url": "https://cen.acs.org/rss/latest.xml"},
    {"name": "MRS Bulletin 材料研究",
     "weight": 9,  "tags": ["materials","MRS","research","semiconductor"],
     "url": "https://link.springer.com/search.rss?query=materials+science&search-within=Journal&facet-journal-id=43577"},
    {"name": "Chemical Engineering News",
     "weight": 8,  "tags": ["chemistry","materials","process"],
     "url": "https://news.google.com/rss/search?q=when:48h+allinurl:chemengineering.com+OR+processing.com+materials+advanced&ceid=US:en"},
    # 电池/能源材料
    {"name": "GNews: 固态电池材料",
     "weight": 10, "tags": ["battery","solid-state","lithium","materials"],
     "url": "https://news.google.com/rss/search?q=when:48h+solid+state+battery+lithium+materials+energy+density+breakthrough&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 锂电池新能源",
     "weight": 9,  "tags": ["lithium","battery","EV","energy","China"],
     "url": "https://news.google.com/rss/search?q=when:48h+lithium+battery+新能源+OR+宁德时代+OR+比亚迪+材料&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "GNews: 稀土关键矿产",
     "weight": 9,  "tags": ["rare-earth","materials","China","supply-chain"],
     "url": "https://news.google.com/rss/search?q=when:48h+rare+earth+critical+minerals+China+supply+chain+materials&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 先进材料半导体",
     "weight": 10, "tags": ["materials","semiconductor","SiC","GaN","substrate"],
     "url": "https://news.google.com/rss/search?q=when:48h+advanced+materials+SiC+OR+GaN+OR+碳化硅+semiconductor+power+chip&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 新材料创新",
     "weight": 9,  "tags": ["materials","innovation","China","carbon"],
     "url": "https://news.google.com/rss/search?q=when:48h+新材料+OR+碳纤维+OR+超导+OR+钙钛矿+OR+石墨烯+materials&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    # 机器人/具身智能
    {"name": "GNews: 人形机器人具身",
     "weight": 10, "tags": ["humanoid","robot","embodied","AI","Tesla","Boston"],
     "url": "https://news.google.com/rss/search?q=when:48h+humanoid+robot+embodied+AI+Boston+Dynamics+Optimus+Figure&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 工业机器人自动化",
     "weight": 9,  "tags": ["industrial","robot","automation","manufacturing"],
     "url": "https://news.google.com/rss/search?q=when:48h+industrial+robot+automation+manufacturing+AI+factory&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 中国机器人产业链",
     "weight": 10, "tags": ["China","robot","reducer","motor","supply-chain"],
     "url": "https://news.google.com/rss/search?q=when:48h+中国+人形机器人+OR+减速器+OR+谐波+OR+具身智能+产业链&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "Robotics & Automation News",
     "weight": 8,  "tags": ["robotics","automation","AI","industry"],
     "url": "https://roboticsandautomationnews.com/feed/"},
    {"name": "IEEE Robotics & Automation",
     "weight": 9,  "tags": ["robotics","research","AI","control"],
     "url": "https://news.google.com/rss/search?q=when:48h+IEEE+robotics+automation+AI+control+manipulation&ceid=US:en&hl=en-US&gl=US"},
    # 先进制造
    {"name": "GNews: 智能制造工业AI",
     "weight": 8,  "tags": ["manufacturing","AI","Industry4.0","China"],
     "url": "https://news.google.com/rss/search?q=when:48h+智能制造+OR+工业AI+OR+数字工厂+OR+Industry+4.0+manufacturing&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "GNews: 光伏太阳能材料",
     "weight": 8,  "tags": ["solar","photovoltaic","perovskite","China"],
     "url": "https://news.google.com/rss/search?q=when:48h+solar+perovskite+photovoltaic+materials+efficiency+China&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 核能小堆材料",
     "weight": 7,  "tags": ["nuclear","SMR","energy","materials"],
     "url": "https://news.google.com/rss/search?q=when:48h+nuclear+small+modular+reactor+SMR+materials+AI+energy&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 3D打印增材制造",
     "weight": 7,  "tags": ["3Dprint","additive","manufacturing","materials"],
     "url": "https://news.google.com/rss/search?q=when:48h+3D+printing+additive+manufacturing+materials+aerospace+chip&ceid=US:en&hl=en-US&gl=US"},
]

# ══════════════════════════════════════════════════════
# Tier 5 · 投资 / VC / 一级市场（18个）权重7-10
# ══════════════════════════════════════════════════════
TIER5_INVESTMENT = [
    {"name": "a16z Blog 顶级VC",
     "weight": 10, "tags": ["VC","AI","investment-thesis","semiconductor"],
     "url": "https://a16z.com/feed/"},
    {"name": "Sequoia Capital",
     "weight": 9,  "tags": ["VC","AI","portfolio","China"],
     "url": "https://www.sequoiacap.com/news/feed/"},
    {"name": "TechCrunch 融资",
     "weight": 9,  "tags": ["VC","funding","startups","AI"],
     "url": "https://techcrunch.com/category/venture/feed/"},
    {"name": "Crunchbase News",
     "weight": 9,  "tags": ["VC","M&A","funding","deals"],
     "url": "https://news.crunchbase.com/feed/"},
    {"name": "CB Insights 研究",
     "weight": 9,  "tags": ["VC","market-research","AI","semiconductor"],
     "url": "https://www.cbinsights.com/research/feed/"},
    {"name": "The Information (GNews)",
     "weight": 9,  "tags": ["tech","insider","AI","semiconductor"],
     "url": "https://news.google.com/rss/search?q=when:48h+allinurl:theinformation.com+AI+chip+semiconductor&ceid=US:en"},
    {"name": "GNews: AI融资独角兽",
     "weight": 10, "tags": ["VC","AI","unicorn","funding"],
     "url": "https://news.google.com/rss/search?q=when:48h+AI+startup+funding+series+billion+valuation+raise&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 芯片半导体投资",
     "weight": 10, "tags": ["semiconductor","investment","funding","PE"],
     "url": "https://news.google.com/rss/search?q=when:48h+semiconductor+chip+investment+funding+billion+venture+capital&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 科技并购M&A",
     "weight": 9,  "tags": ["M&A","acquisition","AI","semiconductor"],
     "url": "https://news.google.com/rss/search?q=when:48h+tech+AI+semiconductor+acquisition+merger+deal+billion&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: AI IPO上市",
     "weight": 8,  "tags": ["IPO","AI","public-market","valuation"],
     "url": "https://news.google.com/rss/search?q=when:48h+AI+company+IPO+listing+valuation+public+offering&ceid=US:en&hl=en-US&gl=US"},
    {"name": "GNews: 中国一级市场投资",
     "weight": 9,  "tags": ["China","VC","investment","AI","semiconductor"],
     "url": "https://news.google.com/rss/search?q=when:48h+中国+AI+融资+OR+投资+OR+独角兽+OR+半导体+亿元&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "Hacker News Top",
     "weight": 8,  "tags": ["tech","AI","startups","developer"],
     "url": "https://news.ycombinator.com/rss"},
    {"name": "GNews: A股科技产业链",
     "weight": 9,  "tags": ["A-share","China","semiconductor","AI","stocks"],
     "url": "https://news.google.com/rss/search?q=when:48h+A股+半导体+OR+芯片+OR+AI+产业链+OR+国产替代&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "GNews: 华为产业链",
     "weight": 10, "tags": ["Huawei","supply-chain","China","AI","semiconductor"],
     "url": "https://news.google.com/rss/search?q=when:48h+华为+昇腾+OR+鸿蒙+OR+Mate+供应链+OR+产业链&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "GNews: 中美科技竞争",
     "weight": 9,  "tags": ["US-China","tech","geopolitics","semiconductor"],
     "url": "https://news.google.com/rss/search?q=when:48h+US+China+tech+competition+AI+semiconductor+decoupling&ceid=US:en&hl=en-US&gl=US"},
    {"name": "华尔街见闻",
     "weight": 8,  "tags": ["finance","macro","investment","China"],
     "url": "https://wallstreetcn.com/rss"},
    {"name": "36氪 投融资",
     "weight": 8,  "tags": ["AI","investment","startups","China"],
     "url": "https://36kr.com/feed"},
    {"name": "GNews: 国际资本市场",
     "weight": 7,  "tags": ["macro","rates","markets","Fed"],
     "url": "https://news.google.com/rss/search?q=when:48h+Fed+interest+rate+market+AI+semiconductor+stocks+NASDAQ&ceid=US:en&hl=en-US&gl=US"},
]

# ══════════════════════════════════════════════════════
# Tier 6 · 中文科技媒体（16个）权重7-9
# ══════════════════════════════════════════════════════
TIER6_CHINESE_MEDIA = [
    {"name": "机器之心",
     "weight": 9,  "tags": ["AI","LLM","research","China"],
     "url": "https://www.jiqizhixin.com/rss"},
    {"name": "量子位",
     "weight": 8,  "tags": ["AI","LLM","industry","China"],
     "url": "https://www.qbitai.com/feed"},
    {"name": "虎嗅 科技",
     "weight": 8,  "tags": ["tech","business","analysis","China"],
     "url": "https://www.huxiu.com/rss/0.xml"},
    {"name": "钛媒体",
     "weight": 7,  "tags": ["AI","tech","investment","China"],
     "url": "https://www.tmtpost.com/rss"},
    {"name": "雷锋网 AI",
     "weight": 7,  "tags": ["AI","robots","chips","China"],
     "url": "https://www.leiphone.com/feed"},
    {"name": "Pandaily 中国科技英文",
     "weight": 7,  "tags": ["China-tech","AI","startups"],
     "url": "https://pandaily.com/feed/"},
    {"name": "Technode 中国科技",
     "weight": 7,  "tags": ["China-tech","AI","policy"],
     "url": "https://technode.com/feed/"},
    {"name": "South China Morning Post Tech",
     "weight": 8,  "tags": ["China","tech","policy","geopolitics"],
     "url": "https://www.scmp.com/rss/5/feed"},
    {"name": "GNews: 中国AI产业政策",
     "weight": 9,  "tags": ["China","AI","policy","government"],
     "url": "https://news.google.com/rss/search?q=when:48h+中国+AI+政策+OR+工信部+OR+科技部+人工智能+规划&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "GNews: 中国算力基建",
     "weight": 9,  "tags": ["China","compute","datacenter","AI-infra"],
     "url": "https://news.google.com/rss/search?q=when:48h+中国+算力+OR+数据中心+OR+智算中心+AI+基础设施&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "GNews: 智能驾驶汽车",
     "weight": 8,  "tags": ["autonomous","EV","AI","China","Tesla"],
     "url": "https://news.google.com/rss/search?q=when:48h+自动驾驶+OR+智能驾驶+OR+特斯拉FSD+OR+华为ADS+芯片&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "GNews: 国产大模型中文",
     "weight": 9,  "tags": ["China","LLM","AI","DeepSeek"],
     "url": "https://news.google.com/rss/search?q=when:48h+DeepSeek+OR+通义+OR+Kimi+OR+豆包+OR+文心+大模型&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "GNews: 半导体产业中文",
     "weight": 9,  "tags": ["semiconductor","China","supply-chain"],
     "url": "https://news.google.com/rss/search?q=when:48h+半导体+芯片+产业链+OR+供应链+国产替代+A股&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "GNews: 材料能源中文",
     "weight": 8,  "tags": ["materials","energy","battery","China"],
     "url": "https://news.google.com/rss/search?q=when:48h+新材料+OR+电池+OR+光伏+OR+氢能+OR+稀土+中国&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "GNews: 机器人中文",
     "weight": 9,  "tags": ["robot","China","humanoid","supply-chain"],
     "url": "https://news.google.com/rss/search?q=when:48h+人形机器人+OR+工业机器人+OR+智能制造+China+供应链&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
    {"name": "每日经济新闻科技",
     "weight": 7,  "tags": ["China","finance","tech","A-share"],
     "url": "https://news.google.com/rss/search?q=when:48h+allinurl:nbd.com.cn+半导体+OR+AI+OR+新能源&ceid=CN:zh-Hans&hl=zh-CN&gl=CN"},
]

# ══════════════════════════════════════════════════════
# 汇总
# ══════════════════════════════════════════════════════
ALL_SOURCES = (
    TIER1_FINANCIAL
    + TIER2_SEMICONDUCTOR
    + TIER3_AI
    + TIER4_MATERIALS_ROBOTICS
    + TIER5_INVESTMENT
    + TIER6_CHINESE_MEDIA
)

KEYWORDS_EN = [
    "AI", "artificial intelligence", "LLM", "large language model",
    "GPU", "semiconductor", "chip", "NVIDIA", "TSMC", "Intel", "AMD","ASML",
    "HBM", "CoWoS", "chiplet", "packaging", "foundry", "EUV", "lithography",
    "compute", "datacenter", "inference", "training", "fine-tuning",
    "investment", "venture capital", "VC", "funding", "IPO", "valuation",
    "materials", "battery", "solid-state", "rare-earth", "SiC", "GaN",
    "robot", "humanoid", "embodied", "automation", "manufacturing",
    "agent", "autonomous", "multimodal", "reasoning", "benchmark",
    "OpenAI", "Anthropic", "DeepSeek", "Gemini", "Claude", "GPT",
    "export control", "ban", "US-China", "supply chain", "decoupling",
    "energy", "nuclear", "power", "gigawatt", "carbon",
    "transformer", "open source", "startup", "unicorn", "acquisition",
]

KEYWORDS_CN = [
    "人工智能", "大模型", "半导体", "芯片", "算力", "投资",
    "融资", "IPO", "估值", "智能体", "数据中心", "推理",
    "封装", "光刻机", "HBM", "先进封装", "国产替代",
    "新材料", "碳纤维", "稀土", "固态电池", "碳化硅",
    "机器人", "人形机器人", "具身智能", "减速器", "产业链",
    "训练", "开源", "创业", "并购", "出口管制",
    "英伟达", "英特尔", "台积电", "华为", "昇腾",
    "DeepSeek", "通义", "Kimi", "豆包",
]

KEYWORDS = KEYWORDS_EN + KEYWORDS_CN

if __name__ == "__main__":
    tiers = [
        ("Tier1 顶级财经",    TIER1_FINANCIAL),
        ("Tier2 半导体算力",  TIER2_SEMICONDUCTOR),
        ("Tier3 人工智能",    TIER3_AI),
        ("Tier4 材料机器人",  TIER4_MATERIALS_ROBOTICS),
        ("Tier5 投资VC",      TIER5_INVESTMENT),
        ("Tier6 中文媒体",    TIER6_CHINESE_MEDIA),
    ]
    total = 0
    print("=== 新闻源统计 ===")
    for name, lst in tiers:
        w10 = sum(1 for s in lst if s["weight"] == 10)
        print(f"  {name}: {len(lst)} 个（权重10: {w10}个）")
        total += len(lst)
    print(f"  {'─'*35}")
    print(f"  总计: {total} 个")
    print()
    # 检查重复
    names = [s["name"] for s in ALL_SOURCES]
    dups = [n for n in set(names) if names.count(n) > 1]
    if dups:
        print(f"  ⚠️  重复: {dups}")
    else:
        print("  ✅ 无重复源")
